export const usStates = () => [
    {
        "name": "Alabama",
        "metaphones": ["ALBM"],
        "statehood_year": 1819,
        "ap_abbr": "Ala.",
        "is_territory": false,
        "fips": "01",
        "abbr": "AL",
        "capital": "Montgomery",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Alaska",
        "metaphones": ["ALSK"],
        "statehood_year": 1959,
        "ap_abbr": "Alaska",
        "is_territory": false,
        "fips": "02",
        "abbr": "AK",
        "capital": "Juneau",
        "capital_tz": "America/Anchorage",
        "time_zones": ["America/Anchorage", "America/Adak"]
    },
    {
        "name": "American Samoa",
        "metaphones": ["AMRXNSM"],
        "statehood_year": null,
        "ap_abbr": null,
        "is_territory": true,
        "fips": "60",
        "abbr": "AS",
        "capital": "Pago Pago",
        "capital_tz": "Pacific/Samoa",
        "time_zones": ["Pacific/Samoa"]
    },
    {
        "name": "Arizona",
        "metaphones": ["ARSN"],
        "statehood_year": 1912,
        "ap_abbr": "Ariz.",
        "is_territory": false,
        "fips": "04",
        "abbr": "AZ",
        "capital": "Phoenix",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver"]
    },
    {
        "name": "Arkansas",
        "metaphones": ["ARKNSS"],
        "statehood_year": 1836,
        "ap_abbr": "Ark.",
        "is_territory": false,
        "fips": "05",
        "abbr": "AR",
        "capital": "Little Rock",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "California",
        "metaphones": ["XLFRN"],
        "statehood_year": 1850,
        "ap_abbr": "Calif.",
        "is_territory": false,
        "fips": "06",
        "abbr": "CA",
        "capital": "Sacramento",
        "capital_tz": "America/Los_Angeles",
        "time_zones": ["America/Los_Angeles"]
    },
    {
        "name": "Colorado",
        "metaphones": ["XLRT"],
        "statehood_year": 1876,
        "ap_abbr": "Colo.",
        "is_territory": false,
        "fips": "08",
        "abbr": "CO",
        "capital": "Denver",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver"]
    },
    {
        "name": "Connecticut",
        "metaphones": ["XNTXT", "XNXTXT"],
        "statehood_year": 1788,
        "ap_abbr": "Conn.",
        "is_territory": false,
        "fips": "09",
        "abbr": "CT",
        "capital": "Hartford",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Delaware",
        "metaphones": ["TLWR"],
        "statehood_year": 1787,
        "ap_abbr": "Del.",
        "is_territory": false,
        "fips": "10",
        "abbr": "DE",
        "capital": "Dover",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "District of Columbia",
        "metaphones": ["TSTRXTFXLM"],
        "statehood_year": null,
        "ap_abbr": "D.C.",
        "is_territory": false,
        "fips": "11",
        "abbr": "DC",
        "capital": null,
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Florida",
        "metaphones": ["FLRT", "FLRTS"],
        "statehood_year": 1845,
        "ap_abbr": "Fla.",
        "is_territory": false,
        "fips": "12",
        "abbr": "FL",
        "capital": "Tallahassee",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York", "America/Chicago"]
    },
    {
        "name": "Georgia",
        "metaphones": ["JRJ", "JRK"],
        "statehood_year": 1788,
        "ap_abbr": "Ga.",
        "is_territory": false,
        "fips": "13",
        "abbr": "GA",
        "capital": "Atlanta",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Guam",
        "metaphones": ["KM"],
        "statehood_year": null,
        "ap_abbr": null,
        "is_territory": true,
        "fips": "66",
        "abbr": "GU",
        "capital": "Hag\\u00e5t\\u00f1a",
        "capital_tz": "Pacific/Guam",
        "time_zones": ["Pacific/Guam"]
    },
    {
        "name": "Hawaii",
        "metaphones": ["HW"],
        "statehood_year": 1959,
        "ap_abbr": "Hawaii",
        "is_territory": false,
        "fips": "15",
        "abbr": "HI",
        "capital": "Honolulu",
        "capital_tz": "Pacific/Honolulu",
        "time_zones": ["Pacific/Honolulu"]
    },
    {
        "name": "Idaho",
        "metaphones": ["ITH"],
        "statehood_year": 1890,
        "ap_abbr": "Idaho",
        "is_territory": false,
        "fips": "16",
        "abbr": "ID",
        "capital": "Boise",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver", "America/Los_Angeles"]
    },
    {
        "name": "Illinois",
        "metaphones": ["ILNS"],
        "statehood_year": 1818,
        "ap_abbr": "Ill.",
        "is_territory": false,
        "fips": "17",
        "abbr": "IL",
        "capital": "Springfield",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Indiana",
        "metaphones": ["INTN"],
        "statehood_year": 1816,
        "ap_abbr": "Ind.",
        "is_territory": false,
        "fips": "18",
        "abbr": "IN",
        "capital": "Indianapolis",
        "capital_tz": "America/Indiana/Indianapolis",
        "time_zones": ["America/Indiana/Indianapolis", "America/Indianapolis", "America/Indiana/Winamac", "America/Indiana/Vincennes", "America/Indiana/Vevay", "America/Indiana/Tell_City", "America/Indiana/Petersburg", "America/Indiana/Marengo", "America/Indiana/Knox", "America/Knox_IN"]
    },
    {
        "name": "Iowa",
        "metaphones": ["IW", "IH"],
        "statehood_year": 1846,
        "ap_abbr": "Iowa",
        "is_territory": false,
        "fips": "19",
        "abbr": "IA",
        "capital": "Des Moines",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Kansas",
        "metaphones": ["KNSS"],
        "statehood_year": 1861,
        "ap_abbr": "Kan.",
        "is_territory": false,
        "fips": "20",
        "abbr": "KS",
        "capital": "Topeka",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago", "America/Denver"]
    },
    {
        "name": "Kentucky",
        "metaphones": ["KNTXY", "KNTKY"],
        "statehood_year": 1792,
        "ap_abbr": "Ky.",
        "is_territory": false,
        "fips": "21",
        "abbr": "KY",
        "capital": "Frankfort",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Louisville"]
    },
    {
        "name": "Louisiana",
        "metaphones": ["LXN", "LSN"],
        "statehood_year": 1812,
        "ap_abbr": "La.",
        "is_territory": false,
        "fips": "22",
        "abbr": "LA",
        "capital": "Baton Rouge",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Maine",
        "metaphones": ["MN"],
        "statehood_year": 1820,
        "ap_abbr": "Maine",
        "is_territory": false,
        "fips": "23",
        "abbr": "ME",
        "capital": "Augusta",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Maryland",
        "metaphones": ["MRLNT"],
        "statehood_year": 1788,
        "ap_abbr": "Md.",
        "is_territory": false,
        "fips": "24",
        "abbr": "MD",
        "capital": "Annapolis",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Massachusetts",
        "metaphones": ["MSXSTS"],
        "statehood_year": 1788,
        "ap_abbr": "Mass.",
        "is_territory": false,
        "fips": "25",
        "abbr": "MA",
        "capital": "Boston",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Michigan",
        "metaphones": ["MXKN"],
        "statehood_year": 1837,
        "ap_abbr": "Mich.",
        "is_territory": false,
        "fips": "26",
        "abbr": "MI",
        "capital": "Lansing",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York", "America/Chicago"]
    },
    {
        "name": "Minnesota",
        "metaphones": ["MNST"],
        "statehood_year": 1858,
        "ap_abbr": "Minn.",
        "is_territory": false,
        "fips": "27",
        "abbr": "MN",
        "capital": "Saint Paul",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Mississippi",
        "metaphones": ["MSSP"],
        "statehood_year": 1817,
        "ap_abbr": "Miss.",
        "is_territory": false,
        "fips": "28",
        "abbr": "MS",
        "capital": "Jackson",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Missouri",
        "metaphones": ["MSR", "MSRY"],
        "statehood_year": 1821,
        "ap_abbr": "Mo.",
        "is_territory": false,
        "fips": "29",
        "abbr": "MO",
        "capital": "Jefferson City",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Montana",
        "metaphones": ["MNTN"],
        "statehood_year": 1889,
        "ap_abbr": "Mont.",
        "is_territory": false,
        "fips": "30",
        "abbr": "MT",
        "capital": "Helena",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver"]
    },
    {
        "name": "Nebraska",
        "metaphones": ["NBRSK", "NBRSX"],
        "statehood_year": 1867,
        "ap_abbr": "Neb.",
        "is_territory": false,
        "fips": "31",
        "abbr": "NE",
        "capital": "Lincoln",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago", "America/Denver"]
    },
    {
        "name": "Nevada",
        "metaphones": ["NFT"],
        "statehood_year": 1864,
        "ap_abbr": "Nev.",
        "is_territory": false,
        "fips": "32",
        "abbr": "NV",
        "capital": "Carson City",
        "capital_tz": "America/Los_Angeles",
        "time_zones": ["America/Los_Angeles", "America/Denver"]
    },
    {
        "name": "New Hampshire",
        "metaphones": ["NHMPXR"],
        "statehood_year": 1788,
        "ap_abbr": "N.H.",
        "is_territory": false,
        "fips": "33",
        "abbr": "NH",
        "capital": "Concord",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "New Jersey",
        "metaphones": ["NJRSY"],
        "statehood_year": 1787,
        "ap_abbr": "N.J.",
        "is_territory": false,
        "fips": "34",
        "abbr": "NJ",
        "capital": "Trenton",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "New Mexico",
        "metaphones": ["NMKSX"],
        "statehood_year": 1912,
        "ap_abbr": "N.M.",
        "is_territory": false,
        "fips": "35",
        "abbr": "NM",
        "capital": "Santa Fe",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "New York",
        "metaphones": ["NYRK"],
        "statehood_year": 1788,
        "ap_abbr": "N.Y.",
        "is_territory": false,
        "fips": "36",
        "abbr": "NY",
        "capital": "Albany",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "North Carolina",
        "metaphones": ["NR0XRLN"],
        "statehood_year": 1789,
        "ap_abbr": "N.C.",
        "is_territory": false,
        "fips": "37",
        "abbr": "NC",
        "capital": "Raleigh",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "North Dakota",
        "metaphones": ["NR0TKT", "NTK"],
        "statehood_year": 1889,
        "ap_abbr": "N.D.",
        "is_territory": false,
        "fips": "38",
        "abbr": "ND",
        "capital": "Bismarck",
        "capital_tz": "America/North_Dakota/Center",
        "time_zones": ["America/North_Dakota/Center", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem"]
    },
    {
        "name": "Northern Mariana Islands",
        "metaphones": ["NR0RNMRNSLNTS"],
        "statehood_year": null,
        "ap_abbr": null,
        "is_territory": true,
        "fips": "69",
        "abbr": "MP",
        "capital": "Saipan",
        "capital_tz": "Pacific/Guam",
        "time_zones": ["Pacific/Guam"]
    },
    {
        "name": "Ohio",
        "metaphones": ["OH"],
        "statehood_year": 1803,
        "ap_abbr": "Ohio",
        "is_territory": false,
        "fips": "39",
        "abbr": "OH",
        "capital": "Columbus",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Oklahoma",
        "metaphones": ["OKLHM"],
        "statehood_year": 1907,
        "ap_abbr": "Okla.",
        "is_territory": false,
        "fips": "40",
        "abbr": "OK",
        "capital": "Oklahoma City",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Oregon",
        "metaphones": ["ORKN"],
        "statehood_year": 1859,
        "ap_abbr": "Ore.",
        "is_territory": false,
        "fips": "41",
        "abbr": "OR",
        "capital": "Salem",
        "capital_tz": "America/Los_Angeles",
        "time_zones": ["America/Los_Angeles", "America/Boise"]
    },
    {
        "name": "Pennsylvania",
        "metaphones": ["PNSLFN"],
        "statehood_year": 1787,
        "ap_abbr": "Pa.",
        "is_territory": false,
        "fips": "42",
        "abbr": "PA",
        "capital": "Harrisburg",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Puerto Rico",
        "metaphones": ["PRTRX"],
        "statehood_year": null,
        "ap_abbr": null,
        "is_territory": true,
        "fips": "72",
        "abbr": "PR",
        "capital": "San Juan",
        "capital_tz": "America/Puerto_Rico",
        "time_zones": ["America/Puerto_Rico"]
    },
    {
        "name": "Rhode Island",
        "metaphones": ["RHTSLNT", "RTSLNT"],
        "statehood_year": 1790,
        "ap_abbr": "R.I.",
        "is_territory": false,
        "fips": "44",
        "abbr": "RI",
        "capital": "Providence",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "South Carolina",
        "metaphones": ["S0XRLN", "STXRLN", "SXRL"],
        "statehood_year": 1788,
        "ap_abbr": "S.C.",
        "is_territory": false,
        "fips": "45",
        "abbr": "SC",
        "capital": "Columbia",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "South Dakota",
        "metaphones": ["S0TKT"],
        "statehood_year": 1889,
        "ap_abbr": "S.D.",
        "is_territory": false,
        "fips": "46",
        "abbr": "SD",
        "capital": "Pierre",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago", "America/Denver"]
    },
    {
        "name": "Tennessee",
        "metaphones": ["TNS"],
        "statehood_year": 1796,
        "ap_abbr": "Tenn.",
        "is_territory": false,
        "fips": "47",
        "abbr": "TN",
        "capital": "Nashville",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago", "America/New_York"]
    },
    {
        "name": "Texas",
        "metaphones": ["TKSS"],
        "statehood_year": 1845,
        "ap_abbr": "Texas",
        "is_territory": false,
        "fips": "48",
        "abbr": "TX",
        "capital": "Austin",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago", "America/Denver"]
    },
    {
        "name": "Utah",
        "metaphones": ["UTH", "UTS", "UTR"],
        "statehood_year": 1896,
        "ap_abbr": "Utah",
        "is_territory": false,
        "fips": "49",
        "abbr": "UT",
        "capital": "Salt Lake City",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver"]
    },
    {
        "name": "Vermont",
        "metaphones": ["FRMNT"],
        "statehood_year": 1791,
        "ap_abbr": "Vt.",
        "is_territory": false,
        "fips": "50",
        "abbr": "VT",
        "capital": "Montpelier",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Virgin Islands",
        "metaphones": ["FRJNSLNTS"],
        "statehood_year": null,
        "ap_abbr": null,
        "is_territory": true,
        "fips": "78",
        "abbr": "VI",
        "capital": "Charlotte Amalie",
        "capital_tz": "America/Puerto_Rico",
        "time_zones": ["America/Puerto_Rico"]
    },
    {
        "name": "Virginia",
        "metaphones": ["FRJN"],
        "statehood_year": 1788,
        "ap_abbr": "Va.",
        "is_territory": false,
        "fips": "51",
        "abbr": "VA",
        "capital": "Richmond",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Washington",
        "metaphones": ["WXNKTN"],
        "statehood_year": 1889,
        "ap_abbr": "Wash.",
        "is_territory": false,
        "fips": "53",
        "abbr": "WA",
        "capital": "Olympia",
        "capital_tz": "America/Los_Angeles",
        "time_zones": ["America/Los_Angeles"]
    },
    {
        "name": "West Virginia",
        "metaphones": ["WSTFRJN", "WSTFRKN"],
        "statehood_year": 1863,
        "ap_abbr": "W.Va.",
        "is_territory": false,
        "fips": "54",
        "abbr": "WV",
        "capital": "Charleston",
        "capital_tz": "America/New_York",
        "time_zones": ["America/New_York"]
    },
    {
        "name": "Wisconsin",
        "metaphones": ["WSXNSN"],
        "statehood_year": 1848,
        "ap_abbr": "Wis.",
        "is_territory": false,
        "fips": "55",
        "abbr": "WI",
        "capital": "Madison",
        "capital_tz": "America/Chicago",
        "time_zones": ["America/Chicago"]
    },
    {
        "name": "Wyoming",
        "metaphones": ["YMN", "YMNJ", "WMN"],
        "statehood_year": 1890,
        "ap_abbr": "Wyo.",
        "is_territory": false,
        "fips": "56",
        "abbr": "WY",
        "capital": "Cheyenne",
        "capital_tz": "America/Denver",
        "time_zones": ["America/Denver"]
    }
];
export const countries = () => [
    {name: 'AFGHANISTAN', abbr: 'AF'},
    {name: 'ÅLAND ISLANDS', abbr: 'AX'},
    {name: 'ALBANIA', abbr: 'AL'},
    {name: 'ALGERIA', abbr: 'DZ'},
    {name: 'AMERICAN SAMOA', abbr: 'AS'},
    {name: 'ANDORRA', abbr: 'AD'},
    {name: 'ANGOLA', abbr: 'AO'},
    {name: 'ANGUILLA', abbr: 'AI'},
    {name: 'ANTARCTICA', abbr: 'AQ'},
    {name: 'ANTIGUA AND BARBUDA', abbr: 'AG'},
    {name: 'ARGENTINA', abbr: 'AR'},
    {name: 'ARMENIA', abbr: 'AM'},
    {name: 'ARUBA', abbr: 'W'},
    {name: 'AUSTRALIA', abbr: 'U'},
    {name: 'AUSTRIA', abbr: 'T'},
    {name: 'AZERBAIJAN', abbr: 'Z'},
    {name: 'BAHAMAS', abbr: 'S'},
    {name: 'BAHRAIN', abbr: 'H'},
    {name: 'BANGLADESH', abbr: 'D'},
    {name: 'BARBADOS', abbr: 'B'},
    {name: 'BELARUS', abbr: 'Y'},
    {name: 'BELGIUM', abbr: 'E'},
    {name: 'BELIZE', abbr: 'Z'},
    {name: 'BENIN', abbr: 'J'},
    {name: 'BERMUDA', abbr: 'M'},
    {name: 'BHUTAN', abbr: 'T'},
    {name: 'BOLIVIA', abbr: 'O'},
    {name: 'BONAIRE, SINT EUSTATIUS AND SABA', abbr: 'Q'},
    {name: 'BOSNIA AND HERZEGOVINA', abbr: 'A'},
    {name: 'BOTSWANA', abbr: 'W'},
    {name: 'BOUVET ISLAND', abbr: 'V'},
    {name: 'BRAZIL', abbr: 'R'},
    {name: 'BRITISH INDIAN OCEAN TERRITORY', abbr: 'O'},
    {name: 'BRUNEI DARUSSALAM', abbr: 'N'},
    {name: 'BULGARIA', abbr: 'G'},
    {name: 'BURKINA FASO', abbr: 'F'},
    {name: 'BURUNDI', abbr: 'I'},
    {name: 'CAMBODIA', abbr: 'H'},
    {name: 'CAMEROON', abbr: 'M'},
    {name: 'CANADA', abbr: 'A'},
    {name: 'CAPE VERDE', abbr: 'V'},
    {name: 'CAYMAN ISLANDS', abbr: 'Y'},
    {name: 'CENTRAL AFRICAN REPUBLIC', abbr: 'F'},
    {name: 'CHAD', abbr: 'D'},
    {name: 'CHILE', abbr: 'L'},
    {name: 'CHINA', abbr: 'N'},
    {name: 'CHRISTMAS ISLAND', abbr: 'X'},
    {name: 'COCOS (KEELING) ISLANDS', abbr: 'C'},
    {name: 'COLOMBIA', abbr: 'O'},
    {name: 'COMOROS', abbr: 'M'},
    {name: 'CONGO', abbr: 'G'},
    {name: 'CONGO THE DEMOCRATIC REPUBLIC OF THE', abbr: 'D'},
    {name: 'COOK ISLANDS', abbr: 'K'},
    {name: 'COSTA RICA', abbr: 'R'},
    {name: 'CÔTE D\'IVOIRE', abbr: 'I'},
    {name: 'CROATIA', abbr: 'R'},
    {name: 'CUBA', abbr: 'U'},
    {name: 'CURAÇAO', abbr: 'W'},
    {name: 'CYPRUS', abbr: 'Y'},
    {name: 'CZECH REPUBLIC', abbr: 'Z'},
    {name: 'DENMARK', abbr: 'K'},
    {name: 'DJIBOUTI', abbr: 'J'},
    {name: 'DOMINICA', abbr: 'M'},
    {name: 'DOMINICAN REPUBLIC', abbr: 'O'},
    {name: 'ECUADOR', abbr: 'C'},
    {name: 'EGYPT', abbr: 'G'},
    {name: 'EL SALVADOR', abbr: 'V'},
    {name: 'EQUATORIAL GUINEA', abbr: 'Q'},
    {name: 'ERITREA', abbr: 'R'},
    {name: 'ESTONIA', abbr: 'E'},
    {name: 'ETHIOPIA', abbr: 'T'},
    {name: 'FALKLAND ISLANDS (MALVINAS)', abbr: 'K'},
    {name: 'FAROE ISLANDS', abbr: 'O'},
    {name: 'FIJI', abbr: 'J'},
    {name: 'FINLAND', abbr: 'I'},
    {name: 'FRANCE', abbr: 'R'},
    {name: 'FRENCH GUIANA', abbr: 'F'},
    {name: 'FRENCH POLYNESIA', abbr: 'F'},
    {name: 'FRENCH SOUTHERN TERRITORIES', abbr: 'F'},
    {name: 'GABON', abbr: 'A'},
    {name: 'GAMBIA', abbr: 'M'},
    {name: 'GEORGIA', abbr: 'E'},
    {name: 'GERMANY', abbr: 'E'},
    {name: 'GHANA', abbr: 'H'},
    {name: 'GIBRALTAR', abbr: 'I'},
    {name: 'GREECE', abbr: 'R'},
    {name: 'GREENLAND', abbr: 'L'},
    {name: 'GRENADA', abbr: 'D'},
    {name: 'GUADELOUPE', abbr: 'P'},
    {name: 'GUAM', abbr: 'U'},
    {name: 'GUATEMALA', abbr: 'T'},
    {name: 'GUERNSEY', abbr: 'G'},
    {name: 'GUINEA', abbr: 'N'},
    {name: 'GUINEA-BISSAU', abbr: 'W'},
    {name: 'GUYANA', abbr: 'Y'},
    {name: 'HAITI', abbr: 'T'},
    {name: 'HEARD ISLAND AND MCDONALD ISLANDS', abbr: 'M'},
    {name: 'HOLY SEE (VATICAN CITY STATE)', abbr: 'A'},
    {name: 'HONDURAS', abbr: 'N'},
    {name: 'HONG KONG', abbr: 'K'},
    {name: 'HUNGARY', abbr: 'U'},
    {name: 'ICELAND', abbr: 'S'},
    {name: 'INDIA', abbr: 'N'},
    {name: 'INDONESIA', abbr: 'D'},
    {name: 'IRAN, ISLAMIC REPUBLIC OF', abbr: 'R'},
    {name: 'IRAQ', abbr: 'Q'},
    {name: 'IRELAND', abbr: 'E'},
    {name: 'ISLE OF MAN', abbr: 'M'},
    {name: 'ISRAEL', abbr: 'L'},
    {name: 'ITALY', abbr: 'T'},
    {name: 'JAMAICA', abbr: 'M'},
    {name: 'JAPAN', abbr: 'P'},
    {name: 'JERSEY', abbr: 'E'},
    {name: 'JORDAN', abbr: 'O'},
    {name: 'KAZAKHSTAN', abbr: 'Z'},
    {name: 'KENYA', abbr: 'E'},
    {name: 'KIRIBATI', abbr: 'I'},
    {name: 'KOREA DEMOCRATIC PEOPLE\'S REPUBLIC OF', abbr: 'P'},
    {name: 'KOREA, REPUBLIC OF', abbr: 'R'},
    {name: 'KUWAIT', abbr: 'W'},
    {name: 'KYRGYZSTAN', abbr: 'G'},
    {name: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', abbr: 'A'},
    {name: 'LATVIA', abbr: 'V'},
    {name: 'LEBANON', abbr: 'B'},
    {name: 'LESOTHO', abbr: 'S'},
    {name: 'LIBERIA', abbr: 'R'},
    {name: 'LIBYA', abbr: 'Y'},
    {name: 'LIECHTENSTEIN', abbr: 'I'},
    {name: 'LITHUANIA', abbr: 'T'},
    {name: 'LUXEMBOURG', abbr: 'U'},
    {name: 'MACAO', abbr: 'O'},
    {name: 'NORTHMACEDONIA', abbr: 'K'},
    {name: 'MADAGASCAR', abbr: 'G'},
    {name: 'MALAWI', abbr: 'W'},
    {name: 'MALAYSIA', abbr: 'Y'},
    {name: 'MALDIVES', abbr: 'V'},
    {name: 'MALI', abbr: 'L'},
    {name: 'MALTA', abbr: 'T'},
    {name: 'MARSHALL ISLANDS', abbr: 'H'},
    {name: 'MARTINIQUE', abbr: 'Q'},
    {name: 'MAURITANIA', abbr: 'R'},
    {name: 'MAURITIUS', abbr: 'U'},
    {name: 'MAYOTTE', abbr: 'T'},
    {name: 'MEXICO', abbr: 'X'},
    {name: 'MICRONESIA, FEDERATED STATES OF', abbr: 'M'},
    {name: 'MOLDOVA, REPUBLIC OF', abbr: 'D'},
    {name: 'MONACO', abbr: 'C'},
    {name: 'MONGOLIA', abbr: 'N'},
    {name: 'MONTENEGRO', abbr: 'E'},
    {name: 'MONTSERRAT', abbr: 'S'},
    {name: 'MOROCCO', abbr: 'A'},
    {name: 'MOZAMBIQUE', abbr: 'Z'},
    {name: 'MYANMAR', abbr: 'M'},
    {name: 'NAMIBIA', abbr: 'A'},
    {name: 'NAURU', abbr: 'R'},
    {name: 'NEPAL', abbr: 'P'},
    {name: 'NETHERLANDS', abbr: 'L'},
    {name: 'NEW CALEDONIA', abbr: 'C'},
    {name: 'NEW ZEALAND', abbr: 'Z'},
    {name: 'NICARAGUA', abbr: 'I'},
    {name: 'NIGER', abbr: 'E'},
    {name: 'NIGERIA', abbr: 'G'},
    {name: 'NIUE', abbr: 'U'},
    {name: 'NORFOLK ISLAND', abbr: 'F'},
    {name: 'NORTHERN MARIANA ISLANDS', abbr: 'P'},
    {name: 'NORWAY', abbr: 'O'},
    {name: 'OMAN', abbr: 'M'},
    {name: 'PAKISTAN', abbr: 'K'},
    {name: 'PALAU', abbr: 'W'},
    {name: 'PALESTINIAN AUTHORITY', abbr: 'PA'},
    {name: 'PANAMA', abbr: 'A'},
    {name: 'PAPUA NEW GUINEA', abbr: 'G'},
    {name: 'PARAGUAY', abbr: 'Y'},
    {name: 'PERU', abbr: 'E'},
    {name: 'PHILIPPINES', abbr: 'H'},
    {name: 'PITCAIRN', abbr: 'N'},
    {name: 'POLAND', abbr: 'L'},
    {name: 'PORTUGAL', abbr: 'T'},
    {name: 'PUERTO RICO', abbr: 'R'},
    {name: 'QATAR', abbr: 'A'},
    {name: 'RÉUNION', abbr: 'E'},
    {name: 'ROMANIA', abbr: 'O'},
    {name: 'RUSSIAN FEDERATION', abbr: 'U'},
    {name: 'RWANDA', abbr: 'W'},
    {name: 'SAINT BARTHÉLEMY', abbr: 'L'},
    {name: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', abbr: 'H'},
    {name: 'SAINT KITTS AND NEVIS', abbr: 'N'},
    {name: 'SAINT LUCIA', abbr: 'C'},
    {name: 'SAINT MARTIN (FRENCH PART)', abbr: 'F'},
    {name: 'SAINT PIERRE AND MIQUELON', abbr: 'M'},
    {name: 'SAINT VINCENT AND THE GRENADINES', abbr: 'C'},
    {name: 'SAMOA', abbr: 'S'},
    {name: 'SAN MARINO', abbr: 'M'},
    {name: 'SAO TOME AND PRINCIPE', abbr: 'T'},
    {name: 'SAUDI ARABIA', abbr: 'A'},
    {name: 'SENEGAL', abbr: 'N'},
    {name: 'SERBIA', abbr: 'S'},
    {name: 'SEYCHELLES', abbr: 'C'},
    {name: 'SIERRA LEONE', abbr: 'L'},
    {name: 'SINGAPORE', abbr: 'G'},
    {name: 'SINT MAARTEN (DUTCH PART)', abbr: 'X'},
    {name: 'SLOVAKIA', abbr: 'K'},
    {name: 'SLOVENIA', abbr: 'I'},
    {name: 'SOLOMON ISLANDS', abbr: 'B'},
    {name: 'SOMALIA', abbr: 'O'},
    {name: 'SOUTH AFRICA', abbr: 'A'},
    {name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', abbr: 'S'},
    {name: 'SOUTH SUDAN', abbr: 'S'},
    {name: 'SPAIN', abbr: 'S'},
    {name: 'SRI LANKA', abbr: 'K'},
    {name: 'SUDAN', abbr: 'D'},
    {name: 'SURINAME', abbr: 'R'},
    {name: 'SVALBARD AND JAN MAYEN', abbr: 'J'},
    {name: 'SWAZILAND', abbr: 'Z'},
    {name: 'SWEDEN', abbr: 'E'},
    {name: 'SWITZERLAND', abbr: 'H'},
    {name: 'SYRIAN ARAB REPUBLIC', abbr: 'Y'},
    {name: 'TAIWAN, PROVINCE OF CHINA', abbr: 'W'},
    {name: 'TAJIKISTAN', abbr: 'J'},
    {name: 'TANZANIA, UNITED REPUBLIC OF', abbr: 'Z'},
    {name: 'THAILAND', abbr: 'H'},
    {name: 'TIMOR-LESTE', abbr: 'L'},
    {name: 'TOGO', abbr: 'G'},
    {name: 'TOKELAU', abbr: 'K'},
    {name: 'TONGA', abbr: 'O'},
    {name: 'TRINIDAD AND TOBAGO', abbr: 'T'},
    {name: 'TUNISIA', abbr: 'N'},
    {name: 'TURKEY', abbr: 'R'},
    {name: 'TURKMENISTAN', abbr: 'M'},
    {name: 'TURKS AND CAICOS ISLANDS', abbr: 'C'},
    {name: 'TUVALU', abbr: 'V'},
    {name: 'UGANDA', abbr: 'G'},
    {name: 'UKRAINE', abbr: 'A'},
    {name: 'UNITED ARAB EMIRATES', abbr: 'E'},
    {name: 'UNITED KINGDOM', abbr: 'B'},
    {name: 'URUGUAY', abbr: 'Y'},
    {name: 'UZBEKISTAN', abbr: 'Z'},
    {name: 'VANUATU', abbr: 'U'},
    {name: 'VENEZUELA, BOLIVARIAN REPUBLIC OF', abbr: 'E'},
    {name: 'VIET NAM', abbr: 'N'},
    {name: 'VIRGIN ISLANDS, BRITISH', abbr: 'G'},
    {name: 'VIRGIN ISLANDS, U.S.', abbr: 'I'},
    {name: 'WALLIS AND FUTUNA', abbr: 'F'},
    {name: 'WESTERN SAHARA', abbr: 'H'},
    {name: 'YEMEN', abbr: 'E'},
    {name: 'ZAMBIA', abbr: 'M'},
    {name: 'ZIMBABWE', abbr: 'W'},
];
export const containerOptions = () => ['OT20', 'OT40', 'RF20', 'RF40', 'FR40', 'FR40', 'TK20'];